#! /bin/sh
#	Placed in the Public Domain.

cat >&2 <<EOF
TEST_SSH_SCP			: $TEST_SSH_SCP
TEST_SSH_SSH			: $TEST_SSH_SSH
TEST_SSH_SSHD			: $TEST_SSH_SSHD
TEST_SSH_SSHAGENT		: $TEST_SSH_SSHAGENT
TEST_SSH_SSHADD			: $TEST_SSH_SSHADD
TEST_SSH_SSHKEYGEN		: $TEST_SSH_SSHKEYGEN
TEST_SSH_SSHPKCS11HELPER	: $TEST_SSH_SSHPKCS11HELPER
TEST_SSH_SSHKEYSCAN		: $TEST_SSH_SSHKEYSCAN
TEST_SSH_SFTP			: $TEST_SSH_SFTP
TEST_SSH_SFTPSERVER		: $TEST_SSH_SFTPSERVER
TEST_SSH_IPV6			: $TEST_SSH_IPV6
TEST_SSH_UTF8			: $TEST_SSH_UTF8
TEST_SHELL			: $TEST_SHELL
EXEEXT				: $EXEEXT
OPENSSL				: $OPENSSL
PLINK				: $PLINK
PUTTYGEN			: $PUTTYGEN
CONCH				: $CONCH
EOF
